<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="IResource"
           tests="9"
           failures="1"
           errors="0"
           skipped="0"
           time="19.739">
  <properties />
            <testcase name="TC09_SignUpSuccess" time="15.781" classname="Test.SignUpTest">
                <failure type="org.junit.ComparisonFailure"
                  message="expected:&lt;...esource.smartdev.vn/[signup]&gt; but was:&lt;...esource.smartdev.vn/[verify-email]&gt;"
              >
<![CDATA[org.junit.ComparisonFailure: expected:<...esource.smartdev.vn/[signup]> but was:<...esource.smartdev.vn/[verify-email]>
  org.junit.Assert.assertEquals(Assert.java:115)
  org.junit.Assert.assertEquals(Assert.java:144)
  Common.HelperAction.equals(HelperAction.java:46)
  Test.SignUpTest.TC09_SignUpSuccess(SignUpTest.java:91)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:808)
  org.testng.TestRunner.run(TestRunner.java:603)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
  org.testng.SuiteRunner.run(SuiteRunner.java:326)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.runSuites(TestNG.java:1092)
  org.testng.TestNG.run(TestNG.java:1060)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC04_FirstName_InvalidData" time="0.543" classname="Test.SignUpTest" />
                <testcase name="TC07_Password_InvalidData" time="0.838" classname="Test.SignUpTest" />
                <testcase name="TC02_PersonaIsChecked" time="0.039" classname="Test.SignUpTest" />
                <testcase name="TC03_Blank" time="0.723" classname="Test.SignUpTest" />
                <testcase name="TC06_Email_InvalidData" time="0.641" classname="Test.SignUpTest" />
                <testcase name="TC01_TitleIsDisplayedCorrectly" time="0.211" classname="Test.SignUpTest" />
                <testcase name="TC05_LastName_InvalidData" time="0.484" classname="Test.SignUpTest" />
                <testcase name="TC08_ConfirmPassword_NotMatch" time="0.479" classname="Test.SignUpTest" />
      
</testsuite>
